const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Rotate,
		C3.Behaviors.solid,
		C3.Behaviors.wrap,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAngle
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{Platform2: 0},
	{Rotate: 0},
	{JavaliBOLTJamaicano: 0},
	{Solid: 0},
	{Wrap: 0},
	{Bullet: 0},
	{Ground: 0},
	{Keyboard: 0},
	{Mountains: 0},
	{Box: 0},
	{Pin: 0},
	{Leandro: 0},
	{Spawner01: 0},
	{Spawner02: 0},
	{Spawner03: 0},
	{BackStreet: 0},
	{Text: 0},
	{Trophy: 0},
	{Gold5: 0},
	{Gold10: 0},
	{Gold30: 0},
	{Destroyer: 0},
	{Box2: 0},
	{Objects: 0},
	{JavaPoints: 0},
	{BoxChange: 0}
];

self.InstanceType = {
	JavaliBOLTJamaicano: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mountains: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	Leandro: class extends self.ISpriteInstance {},
	Spawner01: class extends self.ISpriteInstance {},
	Spawner02: class extends self.ISpriteInstance {},
	Spawner03: class extends self.ISpriteInstance {},
	BackStreet: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Trophy: class extends self.ISpriteInstance {},
	Gold5: class extends self.ISpriteInstance {},
	Gold10: class extends self.ISpriteInstance {},
	Gold30: class extends self.ISpriteInstance {},
	Destroyer: class extends self.ISpriteInstance {},
	Box2: class extends self.ISpriteInstance {},
	Objects: class extends self.ISpriteInstance {}
}